version: '3'

services:
  hadoop-namenode:
    image: apache/hadoop:3.3.5
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
    ports:
      - "9870:9870"
    command: [ "/bin/bash", "/start-hdfs.sh" ]


  hadoop-datanode:
    image: apache/hadoop:3.3.5
    container_name: hadoop-datanode
    hostname: hadoop-datanode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_datanode:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - hadoop-namenode
    command: [ "/bin/bash", "/init-datanode.sh" ]
    ports:
      - "9864:9864"
    links:
      - hadoop-namenode:hadoop-namenode

  spark-master:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop

    ports:
      - '8080:8080'
    
    links:
      - hadoop-namenode:hadoop-namenode

  spark-worker:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop

    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    
    ports:
      - '8081:8081'
    
    links:
      - hadoop-namenode:hadoop-namenode

